### PR TITLE
[Tech Debt] Tidy DockingToolButton class

### PR DESCRIPTION
**Pull request by lmsoria**

### CODE REVIEW

**Comment by KestrelAdrian** [comment]
@lmsoria I'm going to have to do a force push in a bit, yesterday I merged the pull requests but forgot to change the message to a conventional commit style.  Can you pick a point to stop amending code, create pull requests and I will then merge everything and then force push the amended repo.  Let me know when you get to this point so I can perform this, you'll obviously need to re-pull the amended repository.

Sorry to anybody else who has cloned or forked for the repo.

I'll look into creating a git policy to prevent me doing this again.

**Comment by lmsoria** [comment]
@KestrelAdrian let me know if I understood correctly: you want me to stop opening PRs for the moment until you perform the force push. If that's the case and you want to include my changes, then the batch of PRs I've opened today would be the last of the `[Tech Debt]` series. Then I have the linux fix and the cmake support branches. Maybe would be of interest to add these two branches. After those branches get merged you would force push the amended repo.

Is my interpretation right? Sorry for my question, I've never dealt with a similar situation.

**Comment by KestrelAdrian** [comment]
> @KestrelAdrian let me know if I understood correctly: you want me to stop opening PRs for the moment until you perform the force push. If that's the case and you want to include my changes, then the batch of PRs I've opened today would be the last of the `[Tech Debt]` series. Then I have the linux fix and the cmake support branches. Maybe would be of interest to add these two branches. After those branches get merged you would force push the amended repo.
> 
> Is my interpretation right? Sorry for my question, I've never dealt with a similar situation.

I need you to be at a point where you have no outstanding work in your repo so that you can pull the repo back down with the forced changes, if you don't do this then you will have a different history to be and you will have trouble with and subsequent changes.

Does that make sense?  I just want to make sure that you don't create a load of changes and are then unable to pull the repo because it's different to mine.

**Comment by KestrelAdrian** [comment]
@lmsoria it will only take me a couple of minutes to fix, at which point you just re-pull the repo and then everything will be good straight away as we will both be in sync and then up to date with the fixed history.

**Comment by lmsoria** [comment]
Ok, got it! Well, if that's the case, I would like to merge these `[Tech Debt]` branches, as well as the [linux fix](https://github.com/lmsoria/dockingpanes/tree/lmsoria/fix-linux-shadow-issues) and the [cmake support](https://github.com/lmsoria/dockingpanes/tree/lmsoria/add-cmake-support). Those are the most significant changes

**Comment by KestrelAdrian** [comment]
Submit pull requests all your changes, let me know when you’re done doing and have submitted all the pull requests and then I will merge them into master and let you know that you should pull the repo again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
